In [2]:
from pandas import DataFrame
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import decomposition
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv('~/Projects/FinalYearProject/customer_segmentation.csv', low_memory=False)
data = data.as_matrix()
data.shape

(635278, 14)

In [4]:
feature1 = data[:, 7:8]
feature2 = data[:, 9:13]
features = np.concatenate((feature1,feature2), axis=1)
features.shape

(635278, 5)

In [5]:
labels = data[:, 13].ravel()
labels.shape

(635278,)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    features, labels, test_size=0.2, random_state=0)

In [7]:
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=3)

In [8]:
trained = clf.fit(X_train,y_train.astype(int))

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [9]:
clf.score(X_test,y_test.astype(int))

0.97067434831885158

In [10]:
y_pred = trained.predict(X_test)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test.astype(int), y_pred.astype(int))

array([[  1566,    555,     11,      0],
       [   543,   2826,    747,     16],
       [    56,    589,   6126,    659],
       [     6,     61,    483, 112812]])

In [11]:
from sklearn.externals import joblib
filename = 'finalized_without_preprocessing_knn.sav'
joblib.dump(clf, filename)

['finalized_without_preprocessing_knn.sav']

In [13]:
from sklearn.metrics import precision_score,recall_score
precision_score(y_test.astype(int), y_pred, average=None)

array([ 0.72132658,  0.70106673,  0.83154608,  0.99405218])

In [14]:
recall_score(y_test.astype(int), y_pred, average=None)

array([ 0.73452158,  0.6839303 ,  0.82449529,  0.99514829])